# Generated by Django 4.2.5 on 2023-09-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_unloading',
            field=models.BooleanField(default=True),
        ),
    ]
