# Generated by Django 4.2.5 on 2023-09-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mover', '0002_vehicle_is_unloading'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selected_item',
            field=models.CharField(choices=[('1-2', '1 - 2 items'), ('3-5', '3 - 5 items'), ('6-10', '6 - 10 items'), ('11-15', '11 - 15 items')], default='1-2', max_length=5),
        ),
    ]
