# Generated by Django 4.2.5 on 2023-09-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mover', '0003_customuser_selected_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='selected_item',
        ),
        migrations.AddField(
            model_name='booking',
            name='note',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_item',
            field=models.CharField(choices=[('1-2', '1 - 2 items'), ('3-5', '3 - 5 items'), ('6-10', '6 - 10 items'), ('11-15', '11 - 15 items')], default='1-2', max_length=5),
        ),
    ]
