# Generated by Django 4.2.5 on 2023-09-19 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mover', '0005_booking_photo_booking_rate_type_booking_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='goods_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_fufuilled',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_fee',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_weight',
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('Truck', 'Truck'), ('Cargo Van', 'Cargo Van'), ('Moving Van', 'Moving Van'), ('Flatbed Truck', 'Flatbed Truck'), ('Box Truck', 'Box Truck'), ('Mini Van', 'Mini Van'), ('Pick Up Truck', 'Pick Up Truck')], default='Truck', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rate_type',
            field=models.CharField(choices=[('FX', 'Fixed'), ('HR', 'Hourly')], default='FX', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_item',
            field=models.CharField(choices=[('1-2', '1 - 2 items'), ('3-5', '3 - 5 items'), ('6-10', '6 - 10 items'), ('11-15', '11 - 15 items')], default='1-2', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('LOAD', 'Load'), ('UNLOAD', 'UnLoad'), ('BOTH', 'Both')], default='LOAD', max_length=100, null=True),
        ),
    ]
