# Generated by Django 4.2.5 on 2023-09-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mover', '0006_remove_booking_goods_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
