# Generated by Django 4.2.5 on 2023-09-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mover', '0008_alter_booking_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='handle_loading',
            field=models.CharField(choices=[(1, 'Carry up/down stairs'), (2, 'Curbside pick-up/drop-off'), (3, 'Elevator'), (4, 'None of the Above')], default=4, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_fufuilled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
