# Generated by Django 4.2.5 on 2023-09-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mover', '0010_alter_booking_handle_loading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('driver', 'Driver'), ('customer', 'Customer')], default='driver', max_length=10, null=True),
        ),
    ]
