# Generated by Django 4.2.5 on 2023-09-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mover', '0011_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
