# Generated by Django 4.2.1 on 2023-08-25 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('model', models.IntegerField()),
                ('carphoto', models.ImageField(upload_to='')),
                ('isAvailable', models.BooleanField(default=True)),
                ('isLoading', models.BooleanField(default=True)),
                ('vehicle_insurance', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DriverSignUp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('isVerified', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=30)),
                ('rateOfService', models.TextField()),
                ('hourlyAmount', models.IntegerField()),
                ('fixedAmount', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('location', models.TextField()),
                ('drivers_license', models.FileField(upload_to='')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoverApp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pickup_location', models.TextField()),
                ('goods_names', models.CharField(max_length=225)),
                ('goods_weight', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoverApp.driversignup')),
            ],
        ),
    ]
